export type {
  CudaMemoryV2 as CudaMemory,
  GpuMetrics,
  ItemLoadedModel as LoadedModel,
  MemoryPeakUsage,
  MemoryUsage,
  MemoryWarnings,
  RamMemoryV2 as RamMemory,
  ResGpuV2 as ResGPU,
  ResMemoryV2 as ResMemory,
  ResServerInfoV2 as ServerInfo,
  ServerCapabilities,
  ServerModelInfo,
  VersionInfoV2 as VersionInfo,
} from "@/lib/openapi-generated/types.gen";
