/**
 * Generate TypeScript types from `src/api/types/openapi.snapshot.json`.
 *
 * Pipeline:
 * 1. Invoke `@hey-api/openapi-ts` programmatically to produce
 * `src/lib/openapi-generated/types.gen.ts` and `index.ts`.
 * 2. Synthesize `src/lib/openapi-generated/aliases.ts` with friendly
 * named aliases for discriminated unions that Pydantic doesn't expose
 * as named schemas (notably `JobRequest`, which lives inlined inside
 * the `POST /sdapi/v2/jobs` request body).
 * 3. Prepend the project header banner to each emitted file.
 * 4. Write-if-changed per file (mirrors `codegen-paramMap.ts` behaviour).
 *
 * Inputs/outputs match the existing `paramMap.generated.ts` convention:
 * output directory is gitignored, ESLint/Prettier-excluded, regenerated
 * on every `pnpm run dev`, `pnpm run prebuild`, and on Vite HMR when the
 * snapshot file is touched.
 *
 * Source of truth: `src/api/types/openapi.snapshot.json` (committed).
 * Refresh: `pnpm run codegen:refresh`.
 */

import fs from "fs";
import path from "path";
import { createClient } from "@hey-api/openapi-ts";

const ROOT = path.resolve(import.meta.dirname ?? __dirname, "..");
const SNAPSHOT_PATH = path.join(ROOT, "src", "api", "types", "openapi.snapshot.json");
const OUTPUT_DIR = path.join(ROOT, "src", "lib", "openapi-generated");

const HEADER = `// @generated by vite/codegen-openapi.ts - DO NOT EDIT
// Source of truth: src/api/types/openapi.snapshot.json
// Refresh: pnpm run codegen:refresh
`;

type JsonValue = string | number | boolean | null | JsonObject | JsonValue[];
interface JsonObject {
  [key: string]: JsonValue;
}

function refToTypeName(ref: string): string | null {
  const prefix = "#/components/schemas/";
  if (!ref.startsWith(prefix)) return null;
  return ref.slice(prefix.length);
}

/**
 * Discover discriminated unions in the snapshot that should be re-exposed
 * as friendly named types. Walks `paths.*.requestBody|responses.*.content`
 * schemas for any `oneOf + discriminator + mapping` block.
 */
interface DiscoveredUnion {
  name: string;
  variants: Array<{ discriminator: string; typeName: string }>;
}

function discoverInlineUnions(snapshot: JsonObject): DiscoveredUnion[] {
  const out: DiscoveredUnion[] = [];

  // The two unions we know need friendly aliases:
  // - JobRequest: POST /sdapi/v2/jobs request body (Pydantic JobRequest TypeAlias)
  // - JobWsEvent: GET /sdapi/v2/jobs/ws-events response (WsEvent TypeAlias)
  // Both are emitted inline because Pydantic's `Annotated[Union, Discriminator]`
  // type aliases don't get their own component schemas.

  const addIfDiscriminated = (name: string, schema: JsonValue) => {
    if (!schema || typeof schema !== "object" || Array.isArray(schema)) return;
    const oneOf = schema["oneOf"];
    const discriminator = schema["discriminator"];
    if (
      !Array.isArray(oneOf) ||
      !discriminator ||
      typeof discriminator !== "object" ||
      Array.isArray(discriminator)
    )
      return;
    const mapping = discriminator["mapping"];
    if (!mapping || typeof mapping !== "object" || Array.isArray(mapping)) return;
    const variants: DiscoveredUnion["variants"] = [];
    for (const [disc, refValue] of Object.entries(mapping)) {
      if (typeof refValue !== "string") continue;
      const typeName = refToTypeName(refValue);
      if (typeName) variants.push({ discriminator: disc, typeName });
    }
    if (variants.length > 0) out.push({ name, variants });
  };

  const jobsPostBody = (
    ((snapshot.paths as JsonObject | undefined)?.["/sdapi/v2/jobs"] as JsonObject | undefined)
      ?.post as JsonObject | undefined
  )?.requestBody as JsonObject | undefined;
  const jobsPostSchema = (
    (jobsPostBody?.content as JsonObject | undefined)?.["application/json"] as
      JsonObject | undefined
  )?.schema;
  if (jobsPostSchema !== undefined) addIfDiscriminated("JobRequest", jobsPostSchema);

  const wsEventsPath = (snapshot.paths as JsonObject | undefined)?.["/sdapi/v2/jobs/ws-events"] as
    JsonObject | undefined;
  const wsEventsResp = (
    (
      ((wsEventsPath?.get as JsonObject | undefined)?.responses as JsonObject | undefined)?.[
        "200"
      ] as JsonObject | undefined
    )?.content as JsonObject | undefined
  )?.["application/json"] as JsonObject | undefined;
  if (wsEventsResp?.schema !== undefined) addIfDiscriminated("JobWsEvent", wsEventsResp.schema);

  return out;
}

function renderAliases(unions: DiscoveredUnion[]): string {
  if (unions.length === 0) {
    return `${HEADER}\nexport {};\n`;
  }

  const imports = new Set<string>();
  for (const u of unions) {
    for (const v of u.variants) imports.add(v.typeName);
  }
  const importLine = `import type { ${[...imports].sort().join(", ")} } from "./types.gen";`;

  const aliasBlocks = unions.map((u) => {
    const arms = u.variants
      .map((v) => `  | ({ type: ${JSON.stringify(v.discriminator)} } & ${v.typeName})`)
      .join("\n");
    return `export type ${u.name} =\n${arms};`;
  });

  return `${HEADER}\n${importLine}\n\n${aliasBlocks.join("\n\n")}\n`;
}

function writeIfChanged(filePath: string, content: string): boolean {
  let prev = "";
  try {
    prev = fs.readFileSync(filePath, "utf-8");
  } catch {
    /* first run */
  }
  if (prev === content) return false;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf-8");
  return true;
}

function prependHeader(filePath: string): boolean {
  let body: string;
  try {
    body = fs.readFileSync(filePath, "utf-8");
  } catch {
    return false;
  }
  if (body.startsWith(HEADER)) return false;
  fs.writeFileSync(filePath, HEADER + "\n" + body, "utf-8");
  return true;
}

export async function runCodegen(): Promise<void> {
  if (!fs.existsSync(SNAPSHOT_PATH)) {
    throw new Error(
      `codegen-openapi: snapshot missing at ${SNAPSHOT_PATH}. Run \`pnpm run codegen:refresh\` first.`,
    );
  }

  await createClient({
    input: SNAPSHOT_PATH,
    output: { path: OUTPUT_DIR },
    plugins: ["@hey-api/typescript"],
    logs: { level: "silent" },
  });

  // @hey-api writes types.gen.ts + index.ts. Prepend header banners.
  prependHeader(path.join(OUTPUT_DIR, "types.gen.ts"));
  prependHeader(path.join(OUTPUT_DIR, "index.ts"));

  const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf-8")) as JsonObject;
  const unions = discoverInlineUnions(snapshot);
  const aliasesContent = renderAliases(unions);
  writeIfChanged(path.join(OUTPUT_DIR, "aliases.ts"), aliasesContent);
}

const isMain =
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(import.meta.filename ?? __filename);
if (isMain) {
  try {
    await runCodegen();
    process.stdout.write("codegen-openapi - done.\n");
  } catch (error) {
    process.stderr.write(`codegen-openapi failed: ${(error as Error).message}\n`);
    process.exit(1);
  }
}
