/**
 * Generate the SD.Next hint baseline from `src/data/locale_en.snapshot.json`.
 *
 * Distills every locale entry with a non-empty `hint` into a flat
 * `label.toLowerCase() -> hint` Map, emitted as
 * `src/lib/localeHints.generated.ts`. This is the lower layer of Enso's hint
 * lookup: `parameterHelp.ts` overlays Enso's curated divergences on top, and
 * `getParamHelp(label)` returns the override when present, otherwise this
 * baseline.
 *
 * The lowercase-label key matches the historical Enso lookup contract.
 * Collisions (two entries sharing a label case-insensitively) resolve
 * last-write-wins in snapshot order, the same as the original hand-built Map;
 * context-specific hints that would collide are disambiguated at the call site
 * with an inline `tooltip="..."` instead.
 *
 * Output is gitignored (matched by `src/lib/*.generated.ts`), regenerated on
 * every `pnpm run dev`, `pnpm run prebuild`, and on Vite HMR when the snapshot is
 * touched.
 *
 * Source of truth: `src/data/locale_en.snapshot.json` (committed).
 * Refresh: `pnpm run locale:refresh`.
 */

import fs from "fs";
import path from "path";
import type { LocaleDocument } from "../scripts/locale-shared.ts";

const ROOT = path.resolve(import.meta.dirname ?? __dirname, "..");
const SNAPSHOT_PATH = path.join(ROOT, "src", "data", "locale_en.snapshot.json");
const OUTPUT_PATH = path.join(ROOT, "src", "lib", "localeHints.generated.ts");

const HEADER = `// @generated by vite/codegen-locale.ts - DO NOT EDIT
// Source of truth: src/data/locale_en.snapshot.json
// Refresh: pnpm run locale:refresh
`;

function buildBaseline(doc: LocaleDocument): Map<string, string> {
  const hints = new Map<string, string>();
  for (const entries of Object.values(doc)) {
    for (const entry of entries) {
      if (!entry.hint) continue;
      hints.set(entry.label.toLowerCase(), entry.hint);
    }
  }
  return hints;
}

function render(hints: Map<string, string>): string {
  const pairs = [...hints.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const body = pairs
    .map(([key, hint]) => `  [${JSON.stringify(key)}, ${JSON.stringify(hint)}],`)
    .join("\n");
  return `${HEADER}
/** SD.Next hint baseline keyed by lowercased label. ${pairs.length} entries. */
export const localeHints = new Map<string, string>([
${body}
]);
`;
}

function writeIfChanged(filePath: string, content: string): boolean {
  let prev = "";
  try {
    prev = fs.readFileSync(filePath, "utf-8");
  } catch {
    /* first run */
  }
  if (prev === content) return false;
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf-8");
  return true;
}

export function runCodegen(): void {
  if (!fs.existsSync(SNAPSHOT_PATH)) {
    throw new Error(
      `codegen-locale: snapshot missing at ${SNAPSHOT_PATH}. Run \`pnpm run locale:refresh\` first.`,
    );
  }
  const doc = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, "utf-8")) as LocaleDocument;
  const hints = buildBaseline(doc);
  writeIfChanged(OUTPUT_PATH, render(hints));
}

const isMain =
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(import.meta.filename ?? __filename);
if (isMain) {
  try {
    runCodegen();
    process.stdout.write("codegen-locale - done.\n");
  } catch (error) {
    process.stderr.write(`codegen-locale failed: ${(error as Error).message}\n`);
    process.exit(1);
  }
}
