import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { extractParamsFromTabFile, enrichKeywords } from "./extract-params.ts";
import type { ExtractedParam, ExtractWarning } from "./extract-params.ts";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const TABS_DIR = path.join(repoRoot, "src/components/generation/tabs");
const OUTPUT_PATH = path.join(repoRoot, "src/lib/paramMap.generated.ts");
const SYNONYMS_PATH = path.join(here, "palette-synonyms.json");

interface SynonymsFile {
  groups: string[][];
}

function loadSynonymGroups(): string[][] {
  try {
    const raw = fs.readFileSync(SYNONYMS_PATH, "utf-8");
    const parsed = JSON.parse(raw) as SynonymsFile;
    if (!Array.isArray(parsed.groups)) return [];
    return parsed.groups.filter(
      (g): g is string[] =>
        Array.isArray(g) && g.every((t) => typeof t === "string"),
    );
  } catch {
    return [];
  }
}

const HEADER = [
  "// @generated by vite/codegen-paramMap.ts — DO NOT EDIT",
  "// Run `npm run prebuild` to regenerate. Source of truth: <ParamSlider>/<ParamRow>",
  "// JSX in src/components/generation/tabs/*.tsx.",
  "",
  "import type { ImagesSubTab } from \"@/stores/uiStore\";",
  "",
  "export interface ParamEntry {",
  "  tab: ImagesSubTab;",
  "  section: string;",
  "  param: string;",
  "  label: string;",
  "  keywords: string[];",
  "  help?: string;",
  "  /** HTML-stripped, whitespace-collapsed excerpt of help, for fuzzy search. */",
  "  helpExcerpt?: string;",
  "}",
  "",
].join("\n");

export interface CodegenResult {
  params: ExtractedParam[];
  warnings: ExtractWarning[];
  output: string;
  changed: boolean;
}

export function runCodegen(): CodegenResult {
  const tabFiles = fs
    .readdirSync(TABS_DIR)
    .filter((name) => name.endsWith("Tab.tsx"))
    .map((name) => path.join(TABS_DIR, name))
    .sort();

  const synonymGroups = loadSynonymGroups();
  const allParams: ExtractedParam[] = [];
  const allWarnings: ExtractWarning[] = [];

  for (const file of tabFiles) {
    const sourceText = fs.readFileSync(file, "utf-8");
    const result = extractParamsFromTabFile(file, sourceText);
    allParams.push(...result.params);
    allWarnings.push(...result.warnings);
  }

  // Enrich each entry's keywords with label-derived tokens and synonym expansion.
  for (const entry of allParams) {
    entry.keywords = enrichKeywords(entry, synonymGroups);
  }

  // Validation pass: surface entries the user is unlikely to find.
  for (const entry of allParams) {
    if (!entry.label.trim()) {
      allWarnings.push({
        file: TABS_DIR,
        line: 0,
        message: `entry ${entry.tab}/${entry.section}/${entry.param} has empty label`,
      });
    }
    if (!entry.help && entry.keywords.length <= 1) {
      allWarnings.push({
        file: TABS_DIR,
        line: 0,
        message: `entry ${entry.tab}/${entry.section}/${entry.param} has no help and only label-word keywords — consider adding tooltip + keywords`,
      });
    }
    if (entry.help && entry.help.replace(/<[^>]+>/g, "").trim().length < 15) {
      allWarnings.push({
        file: TABS_DIR,
        line: 0,
        message: `entry ${entry.tab}/${entry.section}/${entry.param} has suspiciously short help text`,
      });
    }
  }

  allParams.sort((a, b) => {
    if (a.tab !== b.tab) return a.tab.localeCompare(b.tab);
    if (a.section !== b.section) return a.section.localeCompare(b.section);
    return a.param.localeCompare(b.param);
  });

  const output = renderOutput(allParams);

  let previous = "";
  try {
    previous = fs.readFileSync(OUTPUT_PATH, "utf-8");
  } catch { /* file does not exist yet */ }

  const changed = previous !== output;
  if (changed) {
    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(OUTPUT_PATH, output, "utf-8");
  }

  return { params: allParams, warnings: allWarnings, output, changed };
}

function renderOutput(params: ExtractedParam[]): string {
  const lines = [HEADER];
  lines.push("export const PARAM_MAP: ParamEntry[] = [");

  let currentTab = "";
  for (const entry of params) {
    if (entry.tab !== currentTab) {
      if (currentTab) lines.push("");
      lines.push(`  // --- ${capitalize(entry.tab)} ---`);
      currentTab = entry.tab;
    }
    lines.push(`  ${renderEntry(entry)},`);
  }

  lines.push("];");
  lines.push("");
  return lines.join("\n");
}

function renderEntry(entry: ExtractedParam): string {
  const parts = [
    `tab: ${jsonStr(entry.tab)}`,
    `section: ${jsonStr(entry.section)}`,
    `param: ${jsonStr(entry.param)}`,
    `label: ${jsonStr(entry.label)}`,
    `keywords: [${entry.keywords.map(jsonStr).join(", ")}]`,
  ];
  if (entry.help) parts.push(`help: ${jsonStr(entry.help)}`);
  if (entry.helpExcerpt) parts.push(`helpExcerpt: ${jsonStr(entry.helpExcerpt)}`);
  return `{ ${parts.join(", ")} }`;
}

function jsonStr(s: string): string {
  return JSON.stringify(s);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const result = runCodegen();
  for (const w of result.warnings) {
    process.stderr.write(`[paramMap codegen] ${path.relative(repoRoot, w.file)}:${w.line} ${w.message}\n`);
  }
  const action = result.changed ? "wrote" : "no change";
  process.stdout.write(
    `[paramMap codegen] ${action} ${path.relative(repoRoot, OUTPUT_PATH)} (${result.params.length} entries, ${result.warnings.length} warnings)\n`,
  );
}
